"""
Django settings for django_course project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r0#ovq97e1y*&f1$805ld1kfe$oj=6c%z^%c^b@r+*9$btc=&j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Configure allauth as authentication backend, allow sign in via email as well as username.
AUTHENTICATION_BACKENDS = [
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend', # ⚠️⚠️ Order matters ! Keep allauth 1st, then default-django backend. So for the Admin panel, it will prioritize E-Mail first, but even if Username is given and it matches, Login is Possible. Generally we tend to Like this behaviour for our Admin Panel ! Not for other users. So we removed the username field from Login/Signup and marked it as REQUIRED = False.⚠️⚠️
    
]



























# Application definitions
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'allauth',
    'allauth.account',
    'allauth.socialaccount', # Creates table to store social account info -> socialaccount_socialaccount, socialaccount_socialapp, socialaccount_socialtoken ! Check DB file bro 😃 MIGRATION NEEDED if you add this after adding only allauth.account and allauth !!!!
    'allauth.socialaccount.providers.github',
]

PROJECT_APPS = [
    'app.apps.AppConfig',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PROJECT_APPS # Combining all apps into one list, keeping things clean.






























# Middleware configuration
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

THIRD_PARTY_MIDDLEWARE = [
     'allauth.account.middleware.AccountMiddleware',
]

MIDDLEWARE += THIRD_PARTY_MIDDLEWARE

















# Code for Enabling debug-toolbar while Running Docker Image - black-box for now📦
if DEBUG:
    INSTALLED_APPS += [
        "debug_toolbar"
    ]
    
    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware"
    ]
    
    import socket
    hostname, unused_aliases, ips = socket.gethostbyname_ex(socket.gethostname())
    
    
    INTERNAL_IPS = [ip[:-1]+"1" for ip in ips] + ['127.0.0.1']

ROOT_URLCONF = 'django_course.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_course.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}












# Customizing User Models --> Overriding Djangos default User Model and also ensuring 
# that in every file requring our user we have to write something like - from app.models import User.
# this setting must be defined before the first migration and never changed after initial migration, as changing it later can break the database schema.
AUTH_USER_MODEL = "app.User"

















# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/


TIME_ZONE = 'Asia/Kolkata'
USE_TZ = True
USE_I18N = True
LANGUAGE_CODE = 'bn' # Default




LANGUAGES = [
    ('en', _('English')),
    ('bn', _('Bengali')),
]


LOCALE_PATHS = [
    BASE_DIR / 'locale/', # Where your translation files will live
]


# AUTHENTICATION PAGES !!
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'account_login'


# ⚠️⚠️⚠️ # allauth Configuration to use E-Mail instead of Username to Login, and make Username optional
# Now Username field will be hidden in Sign-Up form. It will only contain E-Mail and Password fields. Allauth will take care of the username, and auto-generate it from the E-Mail, if something like sonu@gmail.com and sonu@outlook.com, usernames will be sonu1 and sonu2 maybe.
# In the Admin Panel Login, though the field will say "Username" - we have to can use E-Mail also, as authentication_method is now "email", not the default "username". For admin panel we can also use Username, check AUTHENTICATION_BACKENDS above !!! ⚠️⚠️⚠️ 
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = "none"



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
