# Generated by Django 6.0.1 on 2026-01-27 14:07

from django.db import migrations
from django.utils import timezone


def recover_or_create_superuser(apps, schema_editor):
    # Renames superuser if already exists, create new superuser if no superuser exists.
    from django.contrib.auth import get_user_model
    User = get_user_model()
    
    # Grab the first superuser found, regardless of their name
    admin = User.objects.filter(is_superuser=True).first()
    
    if admin:
        admin.username = "sonu64" # Rename them so you know it
        admin.email = "admin@gmail.com"
        admin.set_password("sonu64")
        admin.last_login = timezone.now()
        admin.save()
    else:
        # If no superuser exists at all, create one
        admin = User.objects.create_superuser(username="sonu64", email="admin@gmail.com", password="sonu64", last_login=timezone.now())
        admin.save()
    
              
        

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(recover_or_create_superuser)
    ]