# Generated by Django 6.0.1 on 2026-01-30 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recover_or_auto_create_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('inProgress', 'In Progress'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='twitterPost',
            field=models.TextField(blank=True, default='', verbose_name='Twitter Post'),
        ),
        migrations.AlterField(
            model_name='article',
            name='wordCount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Word Count'),
        ),
    ]
